SOURCES = Allegro.cs AllegroLinuxFunctions.cs AllegroWindowsFunctions.cs \
		  Astronomy.cs CelestialObject.cs IDrawable.cs IObjectInSpace.cs \
		  IRotatingObject.cs Planet.cs Program.cs Satellite.cs ScreenObject.cs \
		  ScreenParameters.cs Star.cs Transformation.cs

Planetarium: $(SOURCES)
	mcs -unsafe $(SOURCES)
